# TIE-bomber
mass_kg: 80
physics_filter_time_s: 0.3
max_thrust_n: 6612.5
brake_factor_nspm: 100
max_pitch_rate_degps: 60
max_yaw_rate_degps: 30
max_roll_rate_degps: 150
drag_coefficient: 0.1
lift_coefficient_slope_pdeg: 0.1
lateral_lift_coefficient_slope_pdeg: 0.05
reference_surface_m2: 10

health: 2500.0
shield: 0.0
shield_regen_rate: 0.0
hit_box_radius_m: 9.0

laser_base_range_m: 1500
laser_color: green
laser_fire_rate: 8
cannon_positions: [[-0.5, 1, -1], [0.5, 1, -1]]
laser_sound: sounds/weapons/TIE_BLASTER.mp3
shot_power: 80.0
explosion_scale: 5.0

exterior_engine_sound: sounds/engines/tie_fighter/tie_scream_med.wav
