# TIE-fighter
mass_kg: 100
physics_filter_time_s: 0.3
max_thrust_n: 11250
brake_factor_nspm: 100
max_pitch_rate_degps: 50
max_yaw_rate_degps: 25
max_roll_rate_degps: 130
drag_coefficient: 0.1
lift_coefficient_slope_pdeg: 0.1
lateral_lift_coefficient_slope_pdeg: 0.05
reference_surface_m2: 10

health: 1700.0
shield: 0.0
shield_regen_rate: 0.0
hit_box_radius_m: 6.0

laser_base_range_m: 1500
laser_color: green
laser_fire_rate: 6.7
cannon_positions: [[-0.5, 1, -1], [0.5, 1, -1]]
laser_sound: sounds/weapons/TIE_BLASTER.wav
shot_power: 70.0
explosion_scale: 5.0
death_spin_duration_s: 2.5
death_max_tumble_rate_degps: 400.0

exterior_engine_sound: sounds/engines/tie_common/tie_ext_med.ogg
interior_engine_sound: sounds/engines/tie_common/tie_int_med.ogg
