# TIE-fighter
mass_kg: 20
max_thrust_n: 60000
max_speed_mps: 1000
max_pitch_rate_degps: 60
max_yaw_rate_degps: 30
max_roll_rate_degps: 150
drag_coefficient: 0.1
reference_surface_m2: 10

laser_life_time: 1.5
laser_color: green
laser_fire_rate: 10
cannon_positions: [[-0.5, 1, -1], [0.5, 1, -1]]
laser_sound: sounds/TIE_BLASTER.mp3
