# A-wing
mass_kg: 100
max_thrust_n: 6050
max_pitch_rate_degps: 60
max_yaw_rate_degps: 30
max_roll_rate_degps: 150
drag_coefficient: 0.1
lift_coefficient_slope_pdeg: 0.1
lateral_lift_coefficient_slope_pdeg: 0.05
reference_surface_m2: 10

health: 1300.0
shield: 1200.0
shield_regen_rate: 5.0
hit_box_radius_m: 5.0

laser_base_range_m: 1500
laser_color: red
laser_fire_rate: 8
cannon_positions: [[-3, 5, -1], [3, 5, -1]]
laser_sound: sounds/weapons/XWING_BLASTER.mp3
shot_power: 60.0
explosion_scale: 5.0
